security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider_username:
            entity:
                class: App\Entity\Authentication\User
                property: username
        app_user_provider_email:
            entity:
                class: App\Entity\Authentication\User
                property: email
        app_user_provider_chained:
            chain:
                providers:
                    - app_user_provider_username
                    - app_user_provider_email
        app_user_provider_google:
            id: App\Security\GoogleUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider_chained
            user_checker: App\Security\UserChecker
            form_login:
                login_path: app_login
                check_path: app_login
            custom_authenticators:
                - App\Security\GoogleAuthenticator
            logout:
                path: /logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register/set-password, roles: ROLE_USER }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/resend, roles: PUBLIC_ACCESS }
        - { path: ^/wait, roles: PUBLIC_ACCESS }
        - { path: ^/verify, roles: PUBLIC_ACCESS }
        - { path: /admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
