controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login_google:
    path: /login/google
    controller: App\Controller\Authentication\GoogleLoginController::connect

app_login_google_check:
    path: /login/google/check
