services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Alias pour l'interface UserProviderInterface
    Symfony\Component\Security\Core\User\UserProviderInterface: '@App\Security\GoogleUserProvider'

    # Déclaration de GoogleAuthenticator
    App\Security\GoogleAuthenticator:
        arguments:
            $clientRegistry: '@knpu.oauth2.registry'
            $router: '@router'
            $userProvider: '@App\Security\GoogleUserProvider'  # Injection explicite de GoogleUserProvider
            $entityManager: '@doctrine.orm.entity_manager.abstract'

    App\Security\GoogleUserProvider: ~ # S'assure que le service GoogleUserProvider est défini

    App\Config\AppConfig:
        arguments:
            $noReplyMail: '%env(NO_REPLY_MAIL)%'
            $verifyMailSubject: '%env(VERIFY_MAIL_SUBJECT)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
